import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../api/growth-pathway.js';
import {normalizeStep,acceptPathway,starterPathway} from '../src/growth-pathway.js';
import {integrateLearning} from '../src/learning-integration.js';
const step={title:'Study prayer in 1 Kings 18',objective:'Compare Elijah’s actions and prayer.',success:'Explain context and meaning.',rationale:'Build the foundation before reflection.',type:'study',action:'Peel',duration:25,conceptId:'bad',resourceIds:['r','unknown'],searchQuery:'Elijah prayer 1 Kings 18',resources:[{title:'Source',url:'https://example.org/source',reason:'Context'},{title:'Invented',url:'https://example.org/invented',reason:'Not grounded'}]};
const req={method:'POST',headers:{authorization:'Bearer test'},body:{goal:{title:'Understand prayer'},resources:[{id:'r',title:'Bible'}]}};
function response(){return {setHeader(){},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};}
test('AI API authenticates and only returns resource URLs present in search sources',async()=>{let calls=0;const handler=createHandler({env:{OPENAI_API_KEY:'test'},limits:new Map(),fetcher:async(url,opts)=>{calls++;if(url.endsWith('/user'))return {ok:true,json:async()=>({id:'u'})};const body=JSON.parse(opts.body);assert.equal(body.store,false);assert.equal(body.tools[0].type,'web_search');return {ok:true,json:async()=>({status:'completed',output:[{type:'web_search_call',action:{sources:[{url:'https://example.org/source'}]}},{content:[{type:'output_text',text:JSON.stringify({summary:'Plan',steps:[step]})}]}]})};}});const res=response();await handler(req,res);assert.equal(res.code,200);assert.equal(res.data.pathway.steps[0].resources.length,1);assert.deepEqual(res.data.pathway.steps[0].resourceIds,['r']);assert.equal(res.data.pathway.steps[0].conceptId,'');assert.equal(calls,2);});
test('AI API reports missing configuration, refuses unauthenticated requests',async()=>{const handler=createHandler({env:{},fetcher:async()=>({ok:true,json:async()=>({id:'u'})})});let res=response();await handler(req,res);assert.equal(res.code,503);res=response();await handler({...req,headers:{}},res);assert.equal(res.code,401);});
test('legacy steps normalize, accepting preserves prior work, completion is idempotent',()=>{assert.equal(normalizeStep({kind:'stretch',status:'complete'}).status,'completed');const data={goals:[{id:'g',title:'Prayer',progress:0}],concepts:[],sessions:[],stretches:[],plans:{},learningPlanner:[{id:'old',goalId:'g',status:'completed'}]};const p=starterPathway(data.goals[0],'Elijah',[],[]);let saved=acceptPathway(data,data.goals[0],p);assert.equal(saved.learningPlanner[0].id,'old');const id=saved.learningPlanner[1].id;saved.sessions=[{id:'session',pathwayStepId:id,goalId:'g',actualMs:100}];saved=integrateLearning(integrateLearning(saved));assert.equal(saved.learningPlanner[1].status,'completed');assert.deepEqual(saved.learningPlanner[1].evidenceIds,['session']);assert.equal(saved.goals[0].progress,0);});
