import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../api/growth-pathway.js';
import {normalizeStep,acceptPathway,starterPathway,rankMatches} from '../src/growth-pathway.js';
import {localGrowthPathway} from '../src/local-growth-planner.js';
import {integrateLearning} from '../src/learning-integration.js';
const step={title:'Study prayer',objective:'Compare context.',success:'Explain meaning.',rationale:'Build foundations.',type:'study',action:'Peel',duration:25,conceptId:'bad',resourceIds:['r','unknown'],searchQuery:'Elijah prayer',resources:[{title:'Invented',url:'https://example.org/source',reason:'Unverified'}]};
const req={method:'POST',headers:{authorization:'Bearer test'},body:{goal:{title:'Understand prayer'},resources:[{id:'r',title:'Bible'}]}};
function response(){return {setHeader(){},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};}
test('Gemini authenticates, requests structured JSON and strips invented links and IDs',async()=>{let calls=0;const handler=createHandler({env:{GEMINI_API_KEY:'test',GEMINI_GROWTH_MODEL:'test-model'},limits:new Map(),fetcher:async(url,opts)=>{calls++;if(url.endsWith('/user'))return {ok:true,json:async()=>({id:'u'})};assert.ok(url.endsWith('test-model:generateContent'));assert.equal(opts.headers['x-goog-api-key'],'test');const body=JSON.parse(opts.body);assert.equal(body.generationConfig.responseMimeType,'application/json');assert.ok(body.generationConfig.responseJsonSchema);return {ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({summary:'Plan',steps:[step]})}]}}]})};}});const res=response();await handler(req,res);assert.equal(res.code,200);assert.deepEqual(res.data.pathway.steps[0].resources,[]);assert.deepEqual(res.data.pathway.steps[0].resourceIds,['r']);assert.equal(res.data.pathway.steps[0].conceptId,'');assert.equal(calls,2);});
test('optional API reports missing configuration and refuses unauthenticated requests',async()=>{const handler=createHandler({env:{},fetcher:async()=>({ok:true,json:async()=>({id:'u'})})});let res=response();await handler(req,res);assert.equal(res.code,503);assert.match(res.data.error,/local pathway/);res=response();await handler({...req,headers:{}},res);assert.equal(res.code,401);});
test('Gemini quota failure leaves local planning available',async()=>{const handler=createHandler({env:{GEMINI_API_KEY:'test'},limits:new Map(),fetcher:async url=>url.endsWith('/user')?{ok:true,json:async()=>({id:'u'})}:{ok:false,status:429}});const res=response();await handler(req,res);assert.equal(res.code,429);assert.match(res.data.error,/local pathway/);});
test('local pathways adapt to subject, incorporate gaps, and do not invent resources',()=>{const node={id:'n',title:'Python functions',areaId:'a',parent:'',kind:'concept',status:'Growing',links:[],prerequisites:['Python variables']};const data={lifeAreas:[{id:'a',name:'Career',subAreas:[]}],concepts:[node],notes:[],sessions:[],goals:[],resources:[]};const before=JSON.stringify(data);const goal={id:'g',title:'Learn Python functions',level:'Week'};const p=localGrowthPathway(data,goal,'',[node],[{id:'r',title:'Python reference'},{id:'wrong',title:'Study prayer guide'}]);assert.ok(p.steps.some(s=>s.rationale.startsWith('Recorded knowledge signal:')));assert.ok(p.steps.some(s=>s.type==='stretch'&&s.objective.includes('Test a normal input')));assert.ok(p.steps.every(s=>s.resourceIds.includes('r')&&!s.resourceIds.includes('wrong')&&!s.resources.length));assert.equal(JSON.stringify(data),before);const bible=localGrowthPathway(data,{title:'Study prayer',level:'Day'},'',[],[]);assert.match(bible.summary,/Scripture/);assert.ok(bible.steps.some(s=>s.objective.includes('passage')));assert.ok(bible.steps.every(s=>s.duration<=15));assert.deepEqual(rankMatches([{title:'Study guide'},{title:'Python reference'}],'Study Python'),[{title:'Python reference'}]);});
test('legacy steps normalize, accepting preserves prior work, completion is idempotent',()=>{assert.equal(normalizeStep({kind:'stretch',status:'complete'}).status,'completed');const data={goals:[{id:'g',title:'Prayer',progress:0}],concepts:[],sessions:[],stretches:[],plans:{},learningPlanner:[{id:'old',goalId:'g',status:'completed'}]};const p=starterPathway(data.goals[0],'Elijah',[],[]);let saved=acceptPathway(data,data.goals[0],p);assert.equal(saved.learningPlanner[0].id,'old');const id=saved.learningPlanner[1].id;saved.sessions=[{id:'session',pathwayStepId:id,goalId:'g',actualMs:100}];saved=integrateLearning(integrateLearning(saved));assert.equal(saved.learningPlanner[1].status,'completed');assert.deepEqual(saved.learningPlanner[1].evidenceIds,['session']);assert.equal(saved.goals[0].progress,0);});
