import {test} from 'node:test';
import assert from 'node:assert/strict';
import {integrateLearning} from '../src/learning-integration.js';
import {advanceStudyCycle,nextStudyCycle,focusWallMinutes} from '../src/study-cycles.js';
import {focusedMs} from '../src/model.js';
const day='2026-09-16';
const goal={id:'energy',title:'Energy Economics',level:'Week',targetHours:4,progress:30,due:'2026-09-18'};
const state=()=>({goals:[goal],plans:{},concepts:[{id:'c'}],sessions:[{id:'s',date:day,goalIds:['energy'],actualMs:105*60000,conceptId:'c',completedAt:day}],stretches:[]});
test('completion references are idempotent and reach all linked goals without fabricated evidence',()=>{const data=state();data.goals.push({...goal,id:'second'});data.sessions[0].goalIds.push('second');const once=integrateLearning(data,day),twice=integrateLearning(once,day);assert.equal(twice.goals[1].progress,30);assert.deepEqual(twice.concepts[0].studySessionIds,['s']);assert.equal(twice.sessions.length,1);});
test('focus caps at 25 minutes; breaks never inflate focus; next interval requires resume',()=>{const t={focusCycles:true,planned:50,elapsed:0,started:1000,pauses:[]};assert.equal(focusedMs(t,3601000),1500000);const br=advanceStudyCycle(t,1501000);assert.equal(br.cyclePhase,'break');assert.equal(focusedMs(br,1801000),1500000);assert.equal(nextStudyCycle(br,1502000),br);const next=nextStudyCycle(br,1801000);assert.equal(advanceStudyCycle(next,3301000).cyclePhase,'complete');assert.equal(focusWallMinutes(50),55);});
