import React, {useState,useEffect,useRef} from "react";
import {ArrowUpRight, X, Maximize2, Network, CalendarDays, Sprout} from "lucide-react";
import "./landing-visuals.css";
const previews=[{key:"ecosystem",name:"Knowledge Ecosystem",icon:Network,caption:"A place for every idea. A connection for every discovery.",detail:"Explore a forest, choose a grove, or focus on one part of your knowledge."},{key:"planner",name:"24-hour planner",icon:CalendarDays,caption:"Make room for a full life—and the person you are becoming.",detail:"See commitments, study and recovery together in one realistic daily plan."},{key:"barns",name:"Barns",icon:Sprout,caption:"Bring your effort and your self-assessment into view.",detail:"Reflect on the different capacities you are developing through study and practice."}];
export function ProductShowcase(){const [active,setActive]=useState(0),[expanded,setExpanded]=useState(false);const close=useRef(null),trigger=useRef(null);const current=previews[active];
 useEffect(()=>{if(!expanded)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();const handle=e=>{if(e.key==="Escape")setExpanded(false);if(e.key==="Tab"){e.preventDefault();close.current?.focus();}};window.addEventListener("keydown",handle);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",handle);trigger.current?.focus();};},[expanded]);
 return <section className="product-showcase" id="inside-echostudy"><div className="showcase-orbit" aria-hidden="true"/><div className="showcase-heading"><span className="eyebrow">TAKE A LOOK INSIDE</span><h2>Your growth has<br/><em>a workspace.</em></h2><p>Real views from EchoStudy.<br/>Explore the tools that connect your day.</p></div>
 <div className="showcase-tabs" role="tablist" aria-label="Product previews">{previews.map((v,i)=><button key={v.key} role="tab" id={"preview-tab-"+v.key} aria-selected={active===i} aria-controls="product-preview" onClick={()=>setActive(i)}><v.icon size={18}/>{v.name}</button>)}</div>
 <div className="product-window" id="product-preview" role="tabpanel" aria-labelledby={"preview-tab-"+current.key}><div className="product-window-bar"><span aria-hidden="true">● ● ●</span><span>EchoStudy / {current.name}</span><span>DEMO WORKSPACE</span></div><button className="product-image-button" ref={trigger} onClick={()=>setExpanded(true)} aria-label={"Enlarge "+current.name+" screenshot"}><img key={current.key} src={"/previews/"+current.key+".jpg"} alt={current.name+" in EchoStudy, showing demonstration data"} width="1190" height="820" loading="lazy"/><span className="preview-zoom"><Maximize2 size={16}/> Take a closer look</span></button></div>
 <div className="showcase-caption"><h3>{current.caption}</h3><p>{current.detail}</p><span><ArrowUpRight/> Actual app screenshots · Sample content</span></div>
 {expanded&&<div className="preview-lightbox" role="dialog" aria-modal="true" aria-label={current.name+" screenshot"} onClick={()=>setExpanded(false)}><button ref={close} onClick={()=>setExpanded(false)} aria-label="Close screenshot"><X/></button><img src={"/previews/"+current.key+".jpg"} alt={current.name+" enlarged preview"} onClick={e=>e.stopPropagation()}/></div>}
 </section>;
}
export function LivingTree(){const [selected,setSelected]=useState("Feedback");const nodes=[{x:105,y:95,label:"Foundations",fruit:false},{x:480,y:80,label:"Delegation",fruit:false},{x:100,y:265,label:"Feedback",fruit:true},{x:488,y:265,label:"A new question",fruit:true}];
 return <div className="living-tree"><span className="living-tree-label">TOUCH AN IDEA. FOLLOW ITS GROWTH.</span><svg viewBox="0 0 600 365" role="img" aria-label="Animated knowledge tree illustration"><circle cx="300" cy="175" r="136" fill="#e4efff"/><circle cx="300" cy="175" r="160" fill="none" stroke="#a9c5e5" strokeDasharray="3 10"/><g className="living-branches" fill="none" stroke="#173dc5" strokeWidth="6" strokeLinecap="round"><path pathLength="1" d="M300 332V180Q300 95 105 95M300 180Q300 80 480 80M300 200Q300 265 100 265M300 210Q350 265 488 265"/><path d="M300 310Q270 340 235 343M300 310Q330 340 365 343"/></g><path className="living-graft" d="M110 270Q260 385 478 270" stroke="#ff7900" strokeWidth="3" strokeDasharray="6 7" fill="none"/><rect x="213" y="145" width="174" height="70" rx="26" fill="#082b96"/><text x="300" y="173" textAnchor="middle" fill="#fff" fontSize="11" letterSpacing="2">YOUR KNOWLEDGE</text><text x="300" y="197" textAnchor="middle" fill="#fff" fontSize="19" fontWeight="600">People Management</text>{nodes.map((n,i)=><g key={n.label} role="button" tabIndex="0" aria-label={"Explore "+n.label} onClick={()=>setSelected(n.label)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(n.label);}}} className="living-node"><circle className="node-halo" cx={n.x} cy={n.y} r="42" fill={selected===n.label?"#ffd7b0":"transparent"}/>{n.fruit?<><path d={`M${n.x} ${n.y-22}q5 -25 25 -20q-8 23 -25 20`} fill="#009cde"/><circle cx={n.x} cy={n.y} r="25" fill="#ff7900"/><path d={`M${n.x-12} ${n.y-10}q-7 8 -2 17`} stroke="white" strokeWidth="3" fill="none"/></>:<path d={`M${n.x-30} ${n.y+14}Q${n.x-30} ${n.y-43} ${n.x+32} ${n.y-23}Q${n.x+42} ${n.y+34} ${n.x-30} ${n.y+14}`} fill="#009cde"/>}<rect x={n.x-69} y={n.y+39} width="138" height="29" rx="14" fill="white"/><text x={n.x} y={n.y+58} textAnchor="middle" fill="#082b96" fontSize="13">{n.label}</text></g>)}</svg><p aria-live="polite"><strong>{selected}</strong> · {selected==="A new question"?"Plant the seed of your next discovery.":selected==="Feedback"?"A fruit to Peel, Chew, recall and understand.":selected==="Foundations"?"Strong roots support deeper understanding.":"Grow a branch of specialized knowledge."}</p><small>Interactive illustration</small></div>;
}
export function CapacityIllustration(){return <div className="capacity-illustration"><span className="eyebrow">MANY DIMENSIONS. ROOM TO GROW.</span><div className="capacity-cups">{["Communication","Leadership","Emotional"].map((name,i)=><div key={name} className="capacity-cup-item" style={{"--fill":(44+i*14)+"%","--delay":i*.7+"s"}}><div className="capacity-drop"/><div className="capacity-glass"><div className="capacity-water"/><span className="cup-shine"/></div><strong>{name}</strong></div>)}</div><small>Illustrative capacity view · Your own progress appears in Barns</small></div>;}
