import { expandLifeAreas } from "./life-area-expansion.js";
import { addManagementExample } from "./knowledge-example.js";
// The original supplied list, grouped into 16 major areas. Repeated sub-area names
// intentionally belong to different areas (for example, Communication).
const catalog = [
  [
    "faith",
    "Faith & spirituality",
    "#173dc5",
    [
      "Faith and beliefs",
      "Relationship with God / spirituality",
      "Prayer and meditation",
      "Scripture / sacred-text knowledge",
      "Worship",
      "Spiritual disciplines",
      "Discernment",
      "Spiritual gifts/calling",
      "Character and virtue",
      "Purpose and meaning",
      "Service",
      "Spiritual community",
      "Spiritual maturity",
    ],
  ],
  [
    "mind",
    "Mind & intellectual capacity",
    "#009cde",
    [
      "Critical thinking",
      "Analytical reasoning",
      "Logic",
      "Mental models",
      "Systems thinking",
      "Strategic thinking",
      "Creative thinking",
      "Problem solving",
      "Decision-making",
      "Pattern recognition",
      "Intellectual curiosity",
      "General knowledge",
      "Philosophy",
      "Intellectual humility",
      "Learning how to learn",
      "Memory and comprehension",
    ],
  ],
  [
    "emotional",
    "Emotional wellbeing & identity",
    "#ffd7b0",
    [
      "Emotional intelligence",
      "Self-awareness",
      "Emotional regulation",
      "Resilience",
      "Confidence",
      "Self-esteem",
      "Identity",
      "Personal values",
      "Stress management",
      "Patience",
      "Empathy",
      "Emotional maturity",
      "Processing disappointment/failure",
      "Inner peace",
      "Self-control",
    ],
  ],
  [
    "health",
    "Physical health & vitality",
    "#07529a",
    [
      "Nutrition",
      "Exercise",
      "Strength",
      "Cardiovascular fitness",
      "Mobility/flexibility",
      "Sleep",
      "Rest/recovery",
      "Energy",
      "Preventive healthcare",
      "Medical care",
      "Dental health",
      "Vision",
      "Posture",
      "Body composition",
      "Hygiene",
      "Sexual/reproductive health",
      "Healthy aging",
      "Physical appearance/grooming",
    ],
  ],
  [
    "knowledge",
    "Knowledge & education",
    "#dcefff",
    [
      "Formal education",
      "Professional education",
      "Science",
      "Mathematics",
      "Technology",
      "History",
      "Geography",
      "Economics",
      "Politics/government",
      "Law",
      "Psychology",
      "Sociology",
      "Philosophy",
      "Literature",
      "Arts",
      "Religion/theology",
      "Culture",
      "Languages",
      "Current affairs",
      "Interdisciplinary knowledge",
    ],
  ],
  [
    "skills",
    "Skills & competence",
    "#ff7900",
    [
      "Writing",
      "Speaking",
      "Research",
      "Communication",
      "Negotiation",
      "Leadership",
      "Management",
      "Technical skills",
      "Digital literacy",
      "Data literacy",
      "Financial literacy",
      "Business literacy",
      "Project management",
      "Organization",
      "Problem solving",
      "Facilitation",
      "Sales",
      "Networking",
      "Practical/life skills",
      "Craftsmanship",
      "Domain-specific expertise",
    ],
  ],
  [
    "career",
    "Career & professional life",
    "#009cde",
    [
      "Career direction",
      "Professional identity",
      "Employability",
      "Job performance",
      "Professional expertise",
      "Career advancement",
      "Leadership",
      "Professional reputation",
      "Professional network",
      "Mentorship",
      "Portfolio",
      "Credentials/certifications",
      "Compensation",
      "Workplace relationships",
      "Work-life integration",
      "Career transitions",
      "Entrepreneurship as a career path",
    ],
  ],
  [
    "business",
    "Business & entrepreneurship",
    "#173dc5",
    [
      "Entrepreneurship",
      "Business ideas",
      "Product development",
      "Strategy",
      "Operations",
      "Marketing",
      "Sales",
      "Finance",
      "Accounting",
      "Customer understanding",
      "Innovation",
      "Technology",
      "Team building",
      "Hiring",
      "Leadership",
      "Partnerships",
      "Fundraising",
      "Legal/compliance",
      "Scaling",
      "Business systems",
      "Ownership/equity",
    ],
  ],
  [
    "finance",
    "Personal finance & wealth",
    "#07529a",
    [
      "Income",
      "Expenses",
      "Budgeting",
      "Saving",
      "Emergency reserves",
      "Debt",
      "Credit",
      "Investing",
      "Retirement",
      "Taxes",
      "Insurance",
      "Assets",
      "Liabilities",
      "Cash flow",
      "Net worth",
      "Wealth creation",
      "Financial independence",
      "Estate planning",
      "Giving",
      "Financial education",
      "Risk management",
    ],
  ],
  [
    "relationships",
    "Relationships & social life",
    "#ffd7b0",
    [
      "Friendships",
      "Family relationships",
      "Siblings",
      "Parents",
      "Extended family",
      "Mentors",
      "Professional relationships",
      "Community",
      "Social skills",
      "Networking",
      "Conflict resolution",
      "Boundaries",
      "Trust",
      "Communication",
      "Hospitality",
      "Social support",
      "Belonging",
    ],
  ],
  [
    "marriage",
    "Marriage & romantic partnership",
    "#173dc5",
    [
      "Dating/courtship",
      "Partner selection",
      "Marriage preparation",
      "Communication",
      "Friendship within marriage",
      "Emotional intimacy",
      "Physical intimacy",
      "Conflict resolution",
      "Shared values",
      "Shared faith",
      "Roles/responsibilities",
      "Financial partnership",
      "Decision-making",
      "Family planning",
      "Shared goals",
      "Romance",
      "Trust",
      "Commitment",
      "Marriage growth",
    ],
  ],
  [
    "parenting",
    "Parenting & family life",
    "#dcefff",
    [
      "Preparing for parenthood",
      "Pregnancy/birth knowledge",
      "Child development",
      "Parenting philosophy",
      "Attachment",
      "Discipline",
      "Education",
      "Character formation",
      "Spiritual formation",
      "Emotional development",
      "Child health",
      "Child safety",
      "Communication",
      "Family culture",
      "Family traditions",
      "Household responsibilities",
      "Intergenerational relationships",
      "Legacy",
    ],
  ],
  [
    "home",
    "Home & lifestyle",
    "#ff7900",
    [
      "Housing",
      "Home organization",
      "Cleaning",
      "Interior environment",
      "Food/cooking",
      "Clothing",
      "Transportation",
      "Personal possessions",
      "Digital environment",
      "Sustainability",
      "Safety/security",
      "Daily routines",
      "Lifestyle design",
      "Travel",
      "Relocation",
      "Community/neighborhood",
      "Personal administration",
    ],
  ],
  [
    "discipline",
    "Discipline & personal effectiveness",
    "#07529a",
    [
      "Time management",
      "Attention management",
      "Focus",
      "Deep work",
      "Consistency",
      "Habit formation",
      "Routine",
      "Self-control",
      "Delayed gratification",
      "Prioritization",
      "Planning",
      "Execution",
      "Follow-through",
      "Procrastination management",
      "Digital discipline",
      "Energy management",
      "Personal accountability",
      "Review/reflection",
    ],
  ],
  [
    "recreation",
    "Recreation & creative expression",
    "#ffd7b0",
    [
      "Hobbies",
      "Play",
      "Recreation",
      "Travel",
      "Music",
      "Art",
      "Writing",
      "Design",
      "Photography",
      "Dance",
      "Sports",
      "Games",
      "Nature",
      "Entertainment",
      "Exploration",
      "Adventure",
      "Celebration",
      "Rest",
      "Fun",
      "Creative expression",
    ],
  ],
  [
    "purpose",
    "Purpose, contribution & legacy",
    "#009cde",
    [
      "Life purpose",
      "Calling",
      "Personal mission",
      "Vision",
      "Values",
      "Contribution",
      "Service",
      "Volunteering",
      "Mentorship",
      "Community impact",
      "Social impact",
      "Philanthropy",
      "Institution building",
      "Intellectual contribution",
      "Creative contribution",
      "Family legacy",
      "Financial legacy",
      "Knowledge transfer",
      "Succession",
      "What you want to leave behind",
    ],
  ],
];

export function createDefaultLifeAreas() {
  return expandLifeAreas(
    catalog.map(([id, name, color, names]) => ({
      id,
      name,
      color,
      subAreas: names.map((name, index) => ({
        id: `${id}-${index + 1}`,
        name,
      })),
    })),
  );
}

export const LEGACY_GOAL_AREAS = [
  "knowledge",
  "faith",
  "health",
  "career",
  "relationships",
  "finance",
];

// Migration is additive: existing goals, relationships, progress and session
// references retain their IDs. Existing version-2 areas are never reseeded.
export function migrateWorkspace(state) {
  // Upgrade only the previous built-in palette; preserve custom user colors.
  const palette = {
    "#00b7c7": "#009cde",
    "#b00c60": "#173dc5",
    "#658d10": "#07529a",
    "#d7e525": "#ff7900",
    "#bff5f5": "#dcefff",
    "#fadf96": "#ffd7b0",
  };
  const recolor = (value) =>
    Array.isArray(value)
      ? value.map(recolor)
      : value && typeof value === "object"
        ? Object.fromEntries(
            Object.entries(value).map(([key, item]) => [
              key,
              key === "color" && typeof item === "string"
                ? palette[item.toLowerCase()] || item
                : recolor(item),
            ]),
          )
        : value;
  state = recolor(state);
  if (state.version === 2)
    return addManagementExample(
      state.lifeAreaCatalogRevision >= 2
        ? state
        : {
            ...state,
            lifeAreaCatalogRevision: 2,
            lifeAreas: expandLifeAreas(state.lifeAreas),
          },
    );
  if (state.version !== 1) throw new Error("Unsupported workspace version.");
  return addManagementExample({
    ...state,
    version: 2,
    lifeAreaCatalogRevision: 2,
    lifeAreas: createDefaultLifeAreas(),
    goals: state.goals.map(({ domain, ...goal }) => ({
      ...goal,
      areaId: LEGACY_GOAL_AREAS[domain],
      subAreaId: "",
    })),
  });
}

const normalized = (name) => name.trim().toLocaleLowerCase();
export function validateLifeArea(area, areas) {
  if (!area.name.trim()) return "Give this life area a name.";
  if (
    areas.some(
      (a) => a.id !== area.id && normalized(a.name) === normalized(area.name),
    )
  )
    return "A life area with this name already exists.";
  if (!/^#[0-9a-f]{6}$/i.test(area.color)) return "Choose a palette color.";
  const names = area.subAreas.map((s) => normalized(s.name));
  if (names.some((n) => !n))
    return "Name each sub-area or remove its empty row.";
  if (new Set(names).size !== names.length)
    return "Use a different name for each sub-area within this area.";
  return "";
}

export function goalLocation(goal, areas) {
  const area = areas.find((a) => a.id === goal.areaId);
  const sub = area?.subAreas.find((s) => s.id === goal.subAreaId);
  return [area?.name, sub?.name].filter(Boolean).join(" · ");
}
