import React,{useState} from 'react';
import {Button,Modal,Field} from './App';
import {clock,minutes,duration,today} from './model';
import {hasStudy,hasStretch} from './planner-blocks';
import {changePlannerBlock,setPlannerBlockStatus,plannerBlockStatus,recoveryWindows} from './planner-operations';

export default function PlannerTools({block:b,data,date,save,edit,start,stretch,notify}) {
 const [action,setAction]=useState(null),[day,setDay]=useState(date),[time,setTime]=useState(clock(b.start)),[length,setLength]=useState(b.end-b.start),[first,setFirst]=useState(50),[gap,setGap]=useState(10),[error,setError]=useState('');
 const status=plannerBlockStatus(data,date,b),finished=['completed','skipped'].includes(status),active=data.timer?.blockId===b.id;
 const missed=!finished&&!active&&(date<today()||(date===today()&&b.end<=new Date().getHours()*60+new Date().getMinutes()));
 const open=mode=>{setAction(mode);setError('');setDay(date<today()?today():date);setTime(clock(b.start));setLength(b.end-b.start);setFirst(Math.max(1,Math.floor((b.end-b.start-10)/2)));};
 const commit=fn=>{try{save(fn());setAction(null);notify('Plan updated.');}catch(e){setError(e.message);}};
 const mark=status=>commit(()=>setPlannerBlockStatus(data,date,b,status));
 const windows=recoveryWindows(data,today(),b);
 const launch=()=>{try{let target=b,targetDate=date;if(missed){const now=new Date(),at=now.getHours()*60+now.getMinutes();const next=changePlannerBlock(data,date,b,'move',{date:today(),start:at});target=next.plans[today()].find(x=>x.id===b.id);targetDate=today();save(next);}setAction(null);if(hasStudy(b))start({...target,scheduledDate:targetDate});else stretch({...target,scheduledDate:targetDate});}catch(e){setError(e.message+' Choose Move today to find another opening.');}};
 return <><div className="planner-item-actions">{finished&&<small>{status==='completed'?'Completed':'Skipped'}</small>}{status==='started'&&<small>Started</small>}{missed&&<small className="planner-missed">Not completed yet</small>}<Button onClick={()=>open('menu')}>Actions<span className="sr-only"> for {b.title}</span></Button></div>
 {action&&<Modal title={action==='menu'?b.title:action==='today'?'Move today':action==='delete'?'Remove this block?':`${action==='split'?'Split':action==='duplicate'?'Duplicate':'Move / resize'}: ${b.title}`} onClose={()=>setAction(null)}>
 {action==='menu'?<>{missed&&<p>{b.title} wasn't completed. Choose what works for your day now.</p>}<div className="planner-action-menu">
 {!finished&&<>{hasStudy(b)&&<Button onClick={launch}>{active?'Resume Study':missed?'Start now':hasStretch(b)?'Start Study':'Start'}</Button>}{hasStretch(b)&&<Button onClick={()=>{if(!hasStudy(b))launch();else{setAction(null);stretch({...b,scheduledDate:date});}}}>{hasStudy(b)?'Start Stretch':missed?'Start now':'Start'}</Button>}{!hasStudy(b)&&!hasStretch(b)&&<Button onClick={()=>mark('started')}>Start</Button>}</>}
 <Button onClick={()=>{setAction(null);edit(b);}}>Edit</Button><Button onClick={()=>open('move')}>{missed?'Move to another day':'Move'}</Button><Button onClick={()=>open('today')}>Move today</Button><Button onClick={()=>open('duplicate')}>Duplicate</Button><Button onClick={()=>open('split')}>Split</Button>{!finished&&<><Button onClick={()=>mark('completed')}>Mark Complete</Button><Button onClick={()=>mark('skipped')}>Skip</Button></>}<Button onClick={()=>open('delete')}>Delete</Button></div><p className="field-help">Edit includes Repeat. Mark Complete records calendar completion; Study time and practice evidence are saved in their workspaces.</p></>
 :action==='today'?<><p>Available openings that fit {duration(b.end-b.start)}. Select a time to move this block.</p><div className="planner-window-results">{windows.map(w=><Button key={w.start} onClick={()=>commit(()=>changePlannerBlock(data,date,b,'move',{date:today(),start:w.start}))}>{clock(w.start)} · {clock(w.end)} · Schedule {clock(w.start)} · {clock(w.start+b.end-b.start)}</Button>)}</div>{!windows.length&&<p>No opening today fits the whole block. Choose another day, or resize or split it first.</p>}<Button onClick={()=>open('move')}>Choose another date or duration</Button></>
 :action==='delete'?<><p>Remove this occurrence from your plan? Saved Study and Stretch evidence will remain.</p><Button onClick={()=>mark('deleted')}>Remove</Button></>
 :<form onSubmit={e=>{e.preventDefault();commit(()=>changePlannerBlock(data,date,b,action,{date:action==='split'?date:day,start:minutes(time),end:minutes(time)+Number(length),first,gap}));}}>
 {action==='split'?<><p>Split {duration(b.end-b.start)} into two sessions and an optional break, keeping the original end time.</p><Field label="First session (minutes)"><input type="number" min="1" required value={first} onChange={e=>setFirst(e.target.value)}/></Field><Field label="Break (minutes)"><input type="number" min="0" required value={gap} onChange={e=>setGap(e.target.value)}/></Field><p>Second session: {Math.max(0,b.end-b.start-Number(first)-Number(gap))} minutes.</p></>:<><Field label="Destination date"><input type="date" required value={day} onChange={e=>setDay(e.target.value)}/></Field><Field label="Start time"><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Duration (minutes)"><input type="number" min="1" max="1440" required value={length} onChange={e=>setLength(e.target.value)}/></Field></>}{b.repeatRuleId&&<p>Only this occurrence changes. Other repeats stay in place.</p>}<Button primary type="submit">Save changes</Button></form>}
 {error&&<p role="alert" className="error">{error}</p>}</Modal>}</>;
}
