import React from 'react';
import {Button} from './App';
import {clock,duration,today} from './model';
import {recurringCommitments,hasStudy,hasStretch} from './planner-blocks';
import {weekDays,shiftWeek} from './planner-week';
import PlannerTools from './PlannerTools';

export default function PlannerWeek({data,date,category,selectDate,openDay,add,edit,start,stretch,save,notify}){
 const days=weekDays(date);
 const matches=b=>category==='all'||category==='study'&&hasStudy(b)||category==='stretch'&&hasStretch(b)||category==='life'&&!hasStudy(b)&&!hasStretch(b);
 return <section aria-label="Week plan" className="planner-week"><div className="planner-week-heading"><Button onClick={()=>selectDate(shiftWeek(date,-1))}>Previous week</Button><strong>{new Date(days[0]+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})} – {new Date(days[6]+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</strong><Button onClick={()=>selectDate(shiftWeek(date,1))}>Next week</Button></div><div className="planner-week-grid">{days.map(day=>{const resolved=recurringCommitments(data,day),blocks=resolved.blocks.filter(matches),booked=resolved.blocks.filter(b=>b.status!=='skipped').reduce((n,b)=>n+b.end-b.start,0);return <section key={day} className={`planner-week-day ${day===today()?'is-today':''}`} aria-label={day}><button className="planner-week-date" onClick={()=>openDay(day)}><span>{new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{new Date(day+'T12:00:00').getDate()}</strong>{day===today()&&<small>Today</small>}</button><small>{duration(Math.max(0,1440-booked))} available</small>{resolved.conflicts.length>0&&<small>{resolved.conflicts.length} repeat conflicts · open day to review</small>}<div className="planner-week-blocks">{blocks.map(b=><article key={b.id} className={`planner-week-block ${hasStretch(b)?'is-stretch':'is-study'} ${!hasStudy(b)&&!hasStretch(b)?'is-life':''}`}><span>{hasStudy(b)&&hasStretch(b)?'Study + Stretch':hasStudy(b)?'Study':hasStretch(b)?'Stretch':'Life'}</span><strong>{b.title}</strong><small>{clock(b.start)}–{clock(b.end)}</small>{b.goalId&&<small className="planner-week-goal">{data.goals.find(g=>g.id===b.goalId)?.title}</small>}<PlannerTools block={b} data={data} date={day} save={save} edit={block=>edit(block,day)} start={block=>start({...block,scheduledDate:block.scheduledDate||day})} stretch={block=>stretch({...block,scheduledDate:block.scheduledDate||day})} notify={notify}/></article>)}{!blocks.length&&<p className="muted">No {category==='all'?'':category+' '}blocks</p>}</div><button className="text-btn" onClick={()=>add(day)}>+ Add block</button></section>;})}</div></section>;
}
