import React,{useRef,useState} from 'react';
import {Button,Modal,Field} from './App';
import {clock,minutes,duration} from './model';
import {changePlannerBlock} from './planner-operations';

export default function PlannerTools({blocks,data,date,save,edit,notify}) {
 const [selected,setSelected]=useState(null),[action,setAction]=useState('move'),[day,setDay]=useState(date),[time,setTime]=useState('09:00'),[length,setLength]=useState(60),[first,setFirst]=useState(50),[gap,setGap]=useState(10),[error,setError]=useState(''),[preview,setPreview]=useState(null);
 const gesture=useRef(null);
 const open=b=>{setSelected(b);setDay(date);setTime(clock(b.start));setLength(b.end-b.start);setFirst(Math.max(1,Math.floor((b.end-b.start-10)/2)));setGap(10);setError('');setAction('move');};
 const apply=(b,mode,options)=>{try{save(changePlannerBlock(data,date,b,mode,options));notify('Time block updated.');return true;}catch(e){setError(e.message);notify(e.message);return false;}};
 const begin=(e,b,resize)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={b,resize,y:e.clientY};setPreview(b);};
 const move=e=>{const g=gesture.current;if(!g)return;const delta=Math.round((e.clientY-g.y)/.75/5)*5;setPreview({...g.b,...(g.resize?{end:Math.min(1440,Math.max(g.b.start+5,g.b.end+delta))}:{start:Math.max(0,Math.min(1440-(g.b.end-g.b.start),g.b.start+delta)),end:Math.max(g.b.end-g.b.start,Math.min(1440,g.b.end+delta))})});};
 const end=()=>{const g=gesture.current;gesture.current=null;if(g&&preview&&(preview.start!==g.b.start||preview.end!==g.b.end))apply(g.b,'move',{start:preview.start,end:preview.end});setPreview(null);};
 return <><details className="card planner-tactile"><summary>Arrange your day <small>Drag · Resize · Duplicate · Move · Split</small></summary><p>Drag a block to move it; drag its bottom edge to resize. Snaps to five minutes. Use Options for precise times, another date, or a split.</p><div className="planner-timeline-scroll"><div className="planner-timeline">{Array.from({length:24},(_,h)=><div className="planner-hour" style={{top:h*45}} key={h}><span>{String(h).padStart(2,'0')}:00</span></div>)}{blocks.map(b=>{const shown=preview?.id===b.id?preview:b;return <div className={`planner-drag-block timeline-${b.kind}`} style={{top:shown.start*.75,height:Math.max(16,(shown.end-shown.start)*.75)}} key={b.id}><button className="planner-drag-body" aria-label={`Drag ${b.title}`} onPointerDown={e=>begin(e,b,false)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;setPreview(null);}}>{clock(shown.start)}–{clock(shown.end)} · {b.title}</button><button className="planner-timeline-options" onClick={()=>open(b)} aria-label={`Options for ${b.title}`}>Options</button><button className="planner-resize" aria-label={`Resize ${b.title}`} onPointerDown={e=>begin(e,b,true)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;setPreview(null);}} /></div>;})}</div></div></details>
 {selected&&<Modal title={`Arrange: ${selected.title}`} onClose={()=>setSelected(null)}><form onSubmit={e=>{e.preventDefault();if(apply(selected,action,{date:action==='split'?date:day,start:minutes(time),end:minutes(time)+Number(length),first,gap}))setSelected(null);}}><Field label="Action"><select aria-label="Block action" value={action} onChange={e=>setAction(e.target.value)}><option value="move">Move / resize</option><option value="duplicate">Duplicate</option><option value="split">Split with a break</option></select></Field>{action==='split'?<><p>Divide {duration(selected.end-selected.start)} into two sessions and an optional break. The original end time stays the same.</p><Field label="First session (minutes)"><input type="number" min="1" required value={first} onChange={e=>setFirst(e.target.value)}/></Field><Field label="Break (minutes)"><input type="number" min="0" required value={gap} onChange={e=>setGap(e.target.value)}/></Field><p>Second session: {Math.max(0,selected.end-selected.start-Number(first)-Number(gap))} minutes.</p></>:<><Field label="Destination date"><input type="date" required value={day} onChange={e=>setDay(e.target.value)}/></Field><button type="button" className="text-btn" onClick={()=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+1);setDay(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);}}>Tomorrow</button><Field label="Start time"><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Duration (minutes)"><input type="number" min="1" max="1440" required value={length} onChange={e=>setLength(e.target.value)}/></Field></>}{selected.repeatRuleId&&<p>This changes only this occurrence. Other repeats stay in place.</p>}{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><Button onClick={()=>{setSelected(null);edit(selected);}}>Edit / Repeat</Button><Button primary type="submit">Save changes</Button></div></form></Modal>}</>;
}
