import React,{useState,useEffect,useRef} from 'react';
import {Button,Field,Modal} from './App';
import {supabase} from './auth';
import {knowledgeEntries} from './knowledge-tree';
import {uid,today} from './model';
import {normalizeStep,rankMatches,starterPathway,acceptPathway,studyActions} from './growth-pathway';
import './growth-pathway.css';
const horizons={Year:'Yearly',Quarter:'Quarterly',Month:'Monthly',Week:'Weekly',Day:'Daily'};
export default function StretchPlanner({data,save,go,initialGoalId,onSelectGoal,onLaunch,onSchedule}){
 const [goalId,setGoalId]=useState(initialGoalId||''),[horizon,setHorizon]=useState(''),[area,setArea]=useState(''),[sub,setSub]=useState(''),[query,setQuery]=useState(''),[context,setContext]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(null),[editing,setEditing]=useState(null),[scheduling,setScheduling]=useState(null),[scheduleDate,setScheduleDate]=useState(today());
 const request=useRef(null);useEffect(()=>()=>request.current?.abort(),[]);
 const goal=data.goals.find(g=>g.id===goalId),knowledge=knowledgeEntries(data).filter(n=>!n.trashedAt);
 const visible=data.goals.filter(g=>(!horizon||g.level===horizon)&&[{areaId:g.areaId,subAreaId:g.subAreaId},...(g.locations||[])].some(l=>(!area||l.areaId===area)&&(!sub||l.subAreaId===sub))&&g.title.toLowerCase().includes(query.toLowerCase()));
 const steps=(data.learningPlanner||[]).filter(s=>s.goalId===goalId).map(normalizeStep).sort((a,b)=>(a.order||0)-(b.order||0));
 const select=id=>{request.current?.abort();setBusy(false);setGoalId(id);onSelectGoal?.(id);setContext('');setPreview(null);setError('');};
 const store=step=>save(d=>({...d,learningPlanner:(d.learningPlanner||[]).map(x=>x.id===step.id?step:x)}));
 const generate=async()=>{setBusy(true);setError('');setPreview(null);const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),75000);try{const {data:auth}=await supabase.auth.getSession();if(!auth.session)throw Error('Please sign in again.');const relevant=rankMatches(knowledge,goal.title+' '+context).slice(0,20);const resources=rankMatches(data.resources,goal.title+' '+context).slice(0,20);const response=await fetch('/api/growth-pathway',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth.session.access_token},signal:controller.signal,body:JSON.stringify({goal:{title:goal.title,level:goal.level,due:goal.due,area:data.lifeAreas.find(a=>a.id===goal.areaId)?.name},context,knowledge:relevant.map(n=>({id:n.id,title:n.title,status:n.status})),resources:resources.map(r=>({id:r.id,title:r.title,kind:r.kind,url:r.url}))})});let result;try{result=await response.json();}catch{throw Error('AI generation is unavailable on this deployment. Use the editable starter or try again later.');}if(!response.ok)throw Error(result.error||'Could not generate a pathway.');if(!Array.isArray(result.pathway?.steps)||!result.pathway.steps.length)throw Error('The pathway was incomplete.');setPreview({...result.pathway,mode:'AI + web search',goalId});}catch(e){if(request.current===controller)setError(controller.signal.aborted?'Generation was interrupted. Your saved steps are unchanged.':e.message);}finally{clearTimeout(timeout);if(request.current===controller)setBusy(false);}};
 const resourceLinks=step=><div className="growth-step-resources">{step.resourceIds.map(id=>{const r=data.resources.find(x=>x.id===id);return r&&<div key={id}><strong>Library · {r.title}</strong><small>Carried into the session when selected below.</small></div>;})}{step.resources.filter(r=>/^https:\/\//.test(r.url)).map(r=><div key={r.url}><a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a><small>{r.reason} · Web source</small><Button onClick={()=>{const existing=data.resources.find(x=>x.url===r.url);if(existing){store({...step,resourceIds:[...new Set([...step.resourceIds,existing.id])]});return;}const id=uid();save(d=>({...d,resources:[...d.resources,{id,title:r.title,kind:'url',url:r.url,notes:r.reason||'',tags:[],added:new Date().toISOString(),status:'not-started',concepts:[],knowledgeIds:step.conceptId?[step.conceptId]:[],goalId:step.goalId,locations:[],highlights:[]}],learningPlanner:(d.learningPlanner||[]).map(x=>x.id===step.id?{...x,resourceIds:[...(x.resourceIds||[]),id]}:x)}));}}>Save to library</Button></div>)}{!step.resources.length&&<div><small>Search suggestions — these are not verified resource recommendations.</small><a href={`https://www.youtube.com/results?search_query=${encodeURIComponent(step.searchQuery)}`} target="_blank" rel="noreferrer">Find videos ↗</a><a href={`https://www.google.com/search?tbm=bks&q=${encodeURIComponent(step.searchQuery)}`} target="_blank" rel="noreferrer">Find books ↗</a></div>}</div>;
 return <div className="growth-pathway"><header className="growth-pathway-hero"><span className="eyebrow">GROWTH PLANNER</span><h2>Turn a goal into your next steps.</h2><p>Choose your direction. Build a pathway of learning, practice and evidence. Start now or give each step a place in your day.</p></header><section className="card growth-goal-selection"><h3>Choose a goal</h3><div className="form-grid"><Field label="Goal horizon"><select disabled={busy} value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="">All horizons</option>{Object.entries(horizons).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Life area"><select disabled={busy} value={area} onChange={e=>{setArea(e.target.value);setSub('');}}><option value="">All life areas</option>{data.lifeAreas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Sub-life area"><select disabled={!area||busy} value={sub} onChange={e=>setSub(e.target.value)}><option value="">All sub-areas</option>{data.lifeAreas.find(a=>a.id===area)?.subAreas.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><input aria-label="Search goals for pathway" placeholder="Find your goal…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="growth-goal-options">{visible.map(g=><button disabled={busy} key={g.id} aria-pressed={g.id===goalId} onClick={()=>select(g.id)}><small>{horizons[g.level]}</small><strong>{g.title}</strong></button>)}</div>{!visible.length&&<p>No goals match these filters. Adjust them or create a goal in Goals.</p>}</section>
 {goal&&<><section className="card growth-context"><span className="eyebrow">SELECTED GOAL · {horizons[goal.level]}</span><h2>{goal.title}</h2><Field label="What should this pathway focus on? (optional)"><textarea value={context} disabled={busy} onChange={e=>setContext(e.target.value)} placeholder="Your starting level, a specific topic, constraints, or what you find difficult…"/></Field><p className="field-help">AI uses this goal, your context and relevant knowledge/resource titles. It searches for learning sources and proposes an editable plan.</p><div className="form-actions"><Button primary disabled={busy} onClick={generate}>{busy?'Building your pathway…':'Generate pathway with AI'}</Button><Button disabled={busy} onClick={()=>setPreview({...starterPathway(goal,context,knowledge,data.resources),mode:'Editable starter',goalId})}>Build editable starter</Button></div>{error&&<p role="alert" className="error">{error}</p>}</section>
 {preview&&preview.goalId===goalId&&<section className="card growth-preview"><span className="eyebrow">REVIEW · {preview.mode}</span><p>{preview.summary}</p><ol>{preview.steps.map((s,i)=><li key={i}><strong>{s.title}</strong><p>{s.objective}</p><small>{s.type} · {s.action} · {s.duration} min</small></li>)}</ol><Button primary onClick={()=>{save(d=>acceptPathway(d,goal,preview));setPreview(null);}}>Add these steps to my pathway</Button><Button onClick={()=>setPreview(null)}>Discard preview</Button></section>}
 <div className="section-head"><h2>Your pathway</h2><span>{steps.filter(s=>s.status==='completed').length} / {steps.length} completed</span></div>{!steps.length&&<p>Generate a pathway or build an editable starter to begin.</p>}{steps.map((s,i)=><article className={`card growth-step step-${s.type}`} key={s.id}><header><span className="growth-step-number">{i+1}</span><div><small>{s.type==='study'?'Study':'Stretch'} · {s.action} · {s.duration} min · {s.status}</small><h3>{s.title}</h3></div></header><p>{s.objective}</p>{s.rationale&&<p className="muted">Why this step: {s.rationale}</p>}{s.success&&<p><strong>Evidence to aim for:</strong> {s.success}</p>}<details><summary>Learning resources · {s.resourceIds.length+s.resources.length || 'find sources'}</summary>{resourceLinks(s)}{s.resourceIds.length>0&&<Field label="Resource to open with this step"><select value={s.resourceId||s.resourceIds[0]} onChange={e=>store({...s,resourceId:e.target.value})}>{s.resourceIds.map(id=><option key={id} value={id}>{data.resources.find(r=>r.id===id)?.title||'Resource unavailable'}</option>)}</select></Field>}</details><footer><Button primary disabled={s.status==='completed'} onClick={()=>onLaunch(s)}> {s.type==='study'?'Study now':'Practise now'}</Button><Button disabled={s.status==='completed'} onClick={()=>{setScheduling(s);setScheduleDate(today());}}>Add to Time planner</Button><Button onClick={()=>setEditing(s)}>Edit step</Button><Button onClick={()=>{if(window.confirm('Remove this pathway step? Existing sessions and evidence will be kept.'))save(d=>({...d,learningPlanner:(d.learningPlanner||[]).filter(x=>x.id!==s.id)}));}}>Remove</Button></footer></article>)}</>}
 {goal&&(data.learningPlanner||[]).some(s=>!s.goalId)&&<details className="card growth-context"><summary>Earlier steps without a linked goal</summary>{(data.learningPlanner||[]).filter(s=>!s.goalId).map(s=><p key={s.id}>{s.title} <Button onClick={()=>store({...normalizeStep(s),goalId:goal.id,goalIds:[goal.id]})}>Link to selected goal</Button></p>)}</details>}
 {!goal&&<section className="card empty"><h3>Select a goal to build its pathway.</h3><p>Yearly ambition or today's objective—choose the goal you want to work toward.</p></section>}
 {editing&&<Modal title="Edit pathway step" onClose={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();store(editing);setEditing(null);}}><Field label="Step title"><input required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></Field><Field label="Step objective"><textarea required value={editing.objective} onChange={e=>setEditing({...editing,objective:e.target.value})}/></Field><Field label="Success evidence"><textarea value={editing.success} onChange={e=>setEditing({...editing,success:e.target.value})}/></Field><Field label="Action"><select value={editing.action} onChange={e=>setEditing({...editing,action:e.target.value})}>{(editing.type==='study'?studyActions:['Apply']).map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Minutes"><input required type="number" min="5" max="180" value={editing.duration} onChange={e=>setEditing({...editing,duration:Number(e.target.value)})}/></Field><Field label="Library resource"><select value={editing.resourceId||editing.resourceIds[0]||''} onChange={e=>setEditing({...editing,resourceId:e.target.value,resourceIds:[...new Set([...editing.resourceIds,e.target.value].filter(Boolean))]})}><option value="">Choose resource</option>{data.resources.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></Field><Button primary type="submit">Save step</Button></form></Modal>}
 {scheduling&&<Modal title="Schedule pathway step" onClose={()=>setScheduling(null)}><form onSubmit={e=>{e.preventDefault();onSchedule(scheduling,scheduleDate);setScheduling(null);}}><h3>{scheduling.title}</h3><Field label="Schedule date"><input required type="date" value={scheduleDate} onChange={e=>setScheduleDate(e.target.value)}/></Field><p>Next, review the time, goals and intention in Time planner. Existing scheduled steps open their current block instead of creating a duplicate.</p><Button primary type="submit">Choose time and details</Button></form></Modal>}
 </div>;
}
