import React,{useState} from 'react';
import {Button,Modal,Field} from './App';
import {PlannerGoals} from './PlannerAllocation';
import {uid,today} from './model';
import {recurringCommitments} from './planner-blocks';
import {availableWindows} from './planner-windows';

export default function WeeklyFocus({data,days,category,save,add,notify}) {
 const [draft,setDraft]=useState(null),[scheduling,setScheduling]=useState(null),[date,setDate]=useState(days[0]),[error,setError]=useState('');
 const all=(data.weeklyFocuses||[]).filter(f=>f.week===days[0]);
 const visible=all.filter(f=>category==='all'||f.kind===category);
 const edit=f=>{setError('');setDraft(f||{id:uid(),week:days[0],theme:'',focus:'',outcome:'',activities:'',kind:category==='all'?'study':category,goalIds:[],status:'planned'});};
 const persist=f=>save(d=>({...d,weeklyFocuses:[...(d.weeklyFocuses||[]).filter(x=>x.id!==f.id),f]}));
 return <section className="weekly-focus" aria-label="Weekly focus plans"><header className="weekly-focus-header"><div><span className="eyebrow">THIS WEEK'S SPECIFICS</span><h2>What will you focus on this week?</h2><p>Give an overarching goal a specific theme, person, topic or practical focus. Decide the clock times later.</p></div><Button primary onClick={()=>edit()}>Add weekly focus</Button></header>
 <div className="weekly-focus-grid">{visible.map(f=>{const linked=Object.values(data.plans).flat().filter(b=>b.weeklyFocusId===f.id);return <article className={`weekly-focus-card focus-${f.kind}`} key={f.id}><div className="section-head"><span className="eyebrow">{f.kind==='study'?'Study':f.kind==='stretch'?'Stretch':'Life'} · {f.status==='completed'?'Completed':f.status==='active'?'In progress':'Planned'}</span><button className="text-btn" onClick={()=>edit(f)}>Edit</button></div><h3>{f.theme}</h3><p className="weekly-specific">{f.focus}</p>{f.outcome&&<p><strong>By the end of the week</strong><br/>{f.outcome}</p>}{f.activities&&<details><summary>Weekly plan</summary><p style={{whiteSpace:'pre-wrap'}}>{f.activities}</p></details>}{f.goalIds.length>0&&<div className="weekly-linked-goals"><small>Contributes to</small>{f.goalIds.map(id=><span key={id}>{data.goals.find(g=>g.id===id)?.title||'Goal no longer available'}</span>)}</div>}<footer><small>{linked.length?`${linked.length} daily blocks linked`:'No clock times assigned'}</small><Button onClick={()=>{setScheduling(f);setDate(days.includes(today())?today():days[0]);setError('');}}>Schedule a session</Button></footer></article>;})}</div>
 {!visible.length&&<div className="weekly-focus-empty"><h3>{all.length?'No focus plans in this category yet.':'Turn your goal into this week’s plan.'}</h3><p>Monthly goal: Study prayer through the prophets.<br/>Weekly theme: Prayer.<br/>Specific focus: Elijah — his prayer on Mount Carmel.</p><p>Add as many weekly focuses as you need across your life areas.</p></div>}
 {draft&&<Modal title={all.some(f=>f.id===draft.id)?'Edit weekly focus':'Plan a weekly focus'} onClose={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();if(!draft.theme.trim()||!draft.focus.trim())return;persist({...draft,theme:draft.theme.trim(),focus:draft.focus.trim()});setDraft(null);notify('Weekly focus saved.');}}><p>{days[0]} – {days[6]} · No start or end time required.</p><Field label="Type"><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="study">Study</option><option value="stretch">Stretch</option><option value="life">Life</option></select></Field><Field label="Theme or topic"><input required autoFocus value={draft.theme} onChange={e=>setDraft({...draft,theme:e.target.value})} placeholder="Prayer"/></Field><Field label="Specific focus this week"><input required value={draft.focus} onChange={e=>setDraft({...draft,focus:e.target.value})} placeholder="Elijah — prayer on Mount Carmel"/></Field><Field label="What do you want to understand or do? (optional)"><textarea value={draft.outcome} onChange={e=>setDraft({...draft,outcome:e.target.value})} placeholder="Understand how Elijah's prayer expresses faith and dependence on God."/></Field><Field label="How will you approach it? (optional)"><textarea value={draft.activities} onChange={e=>setDraft({...draft,activities:e.target.value})} placeholder="Read 1 Kings 18. Explore the context. Reflect on prayer. Practise what I learn."/></Field><details open={draft.goalIds.length>0}><summary>Link overarching goals (optional)</summary><PlannerGoals goals={data.goals} areas={data.lifeAreas} value={draft.goalIds} onChange={goalIds=>setDraft({...draft,goalIds})}/></details><Field label="Status"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="planned">Planned</option><option value="active">In progress</option><option value="completed">Completed</option></select></Field><div className="form-actions">{all.some(f=>f.id===draft.id)&&<button type="button" className="text-btn danger" onClick={()=>{if(window.confirm('Remove this weekly focus? Existing daily blocks and goals will be kept.')){save(d=>({...d,weeklyFocuses:(d.weeklyFocuses||[]).filter(f=>f.id!==draft.id)}));setDraft(null);}}}>Remove focus</button>}<Button primary type="submit">Save weekly focus</Button></div></form></Modal>}
 {scheduling&&<Modal title="Choose a day for this focus" onClose={()=>setScheduling(null)}><form onSubmit={e=>{e.preventDefault();const gap=availableWindows(recurringCommitments(data,date).blocks).find(w=>w.end-w.start>=30);if(!gap){setError('No 30-minute opening on this day. Choose another day or free some time in Day view.');return;}const f=scheduling;setScheduling(null);add(date,{id:uid(),title:`${f.theme} — ${f.focus}`,objective:f.outcome||f.focus,kind:f.kind==='study'?'deep':f.kind,goalIds:f.goalIds,goalId:f.goalIds[0]||'',weeklyFocusId:f.id,start:gap.start,end:gap.start+30,repeat:'none',intention:'peel'});}}><p>{scheduling.theme} · {scheduling.focus}</p><Field label="Session day"><select value={date} onChange={e=>setDate(e.target.value)}>{days.map(d=><option key={d} value={d}>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</option>)}</select></Field><p>Next, choose the session’s time and study or practice details. Nothing is scheduled until you save the time block.</p>{error&&<p role="alert" className="error">{error}</p>}<Button primary type="submit">Choose time and details</Button></form></Modal>}
 </section>;
}
